### ISSUE TITLE
running idmlaser on COMPS

### ISSUE THREAD

**Issue by krosenfeld-IDM** [InstituteforDiseaseModeling/laser#18]
I'm using https://github.com/InstituteforDiseaseModeling/laser/commit/f598b877f2b20694a3aaa60ef6bd3a7171eab047 and `run_laser_with_sf.py`. Currently getting error:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/202407_laser/jb_src/src/idmlaser/measles.py", line 17, in <module>
    from . import sir_numpy_c as model
  File "/202407_laser/jb_src/src/idmlaser/sir_numpy_c.py", line 13, in <module>
    import demographics_settings
ModuleNotFoundError: No module named 'demographics_settings'
```
comps info:
https://comps.idmod.org/#explore/Simulations?filters=ExperimentId=f560c9ac-8e43-ef11-aa15-9440c9be2c51&mode=list&orderby=DateCreated+desc&count=10&offset=0&selectedId=4761c9ac-8e43-ef11-aa15-9440c9be2c51

**Comment by krosenfeld-IDM** [comment]
My file directory structure (particularly the placement of `demographics-settings.py` in the `Assets\` folder) matched the successful experiments by @jonathanhhb : https://comps.idmod.org/#explore/Simulations?filters=ExperimentId=b12a9cb9-2741-ef11-aa15-9440c9be2c51&mode=list&orderby=DateCreated+desc&count=10&offset=0&resizer=502C502C0&selectedId=022b9cb9-2741-ef11-aa15-9440c9be2c51

**Comment by krosenfeld-IDM** [comment]
Using notes on running on COMPS from @jonathanhhb 
https://github.com/InstituteforDiseaseModeling/laser/wiki/Running-on-COMPS

**Comment by krosenfeld-IDM** [comment]
This error was due to issues with PYTHONPATH. Note that on COMPS there is an issue with soft link and the Assets folder. See this [Teams thread](https://teams.microsoft.com/l/message/19:kPCMxDcrAVaEtdJ1WdTnbf2CeOxwbXRrAVm4d1Hz9-Y1@thread.tacv2/1721538967727?tenantId=296b3838-4bd5-496c-bd4b-f456ea743b74&groupId=3cef0609-d18f-4e78-b6fe-e5ae3dda97f7&parentMessageId=1721538967727&teamName=Light-Agent%20Spatial%20model%20for%20ERadication&channelName=General&createdTime=1721538967727)
